### ISSUE TITLE
Help running the application 

### ISSUE THREAD

**Issue by sandwichsudo** [armoniaechaos/oct-r-t#6]
Hi 👋 Many thanks for the code test - would you mind double checking it runs as expected for you please? After running `yarn` to install dependencies and then `yarn dev` to start the server and client,

![Screenshot 2023-03-21 at 11 19 01](https://user-images.githubusercontent.com/4517593/226590931-2e893555-38c8-4712-8c7e-d071f64182eb.png)

I can navigate to the home page correctly:

http://localhost:3000/

![Screenshot 2023-03-21 at 11 18 02](https://user-images.githubusercontent.com/4517593/226590808-6c4a7de7-a3aa-4cef-90e4-f4e362fff3c0.png)

but the product page gives the following error:

http://localhost:3000/product/1

![Screenshot 2023-03-21 at 11 15 42](https://user-images.githubusercontent.com/4517593/226590636-5d17605c-2f58-478e-8098-07012bd02065.png)

Thank you,
Gilly

**Comment by sandwichsudo** [comment]
Ahh never mind, I've fixed it by adding an .env file with ```NEXT_PUBLIC_GRAPHQL_URL=http://localhost:3001```

**Comment by armoniaechaos** [comment]
Sorry, i just saw this! Yes, I forgot to remove the .env file from .gitignore, so sorry about this! @sandwichsudo
